# Generated by Django 4.2.1 on 2023-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=10)),
                ('published_data', models.DateTimeField()),
            ],
        ),
    ]
