# Generated by Django 4.2.1 on 2023-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
