# Generated by Django 4.2.1 on 2023-06-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_movies_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='published_data',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_title',
            new_name='title',
        ),
    ]
